# Generated by Django 5.0 on 2023-12-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('service', models.CharField(choices=[('lashes', 'Наращивание ресниц'), ('manicure', 'Маникюр'), ('haircut', 'Стрижка'), ('hairstyle', 'Укладка')], max_length=20)),
                ('appointment_time', models.DateTimeField()),
            ],
        ),
    ]
