# Generated by Django 5.0 on 2023-12-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_appointment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('lashes', 'Наращивание ресниц'), ('manicure', 'Маникюр'), ('haircut', 'Стрижка'), ('hairstyle', 'Укладка')], max_length=20)),
                ('description', models.TextField()),
                ('post_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
